apiVersion: v1
kind: Service
metadata:
  name: integration-service-n-pichuzhkin
spec:
  type: LoadBalancer
  ports:
    - port: 8055
      targetPort: 8055
  selector:
    app: integration-service-n-pichuzhkin
